# Generated by Django 4.0b1 on 2021-11-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191216_0937'),
        ('users', '0003_alter_user_favs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='rooms.Room'),
        ),
    ]
